対応チャンネルの追加
kobi32768/quotebot pull request #28
Opened 2022-08-19 12:11 UTC by Sayamame-beans

VoiceChannel, ThreadChannel, NewsChannelを新たに対応可能にします。 (Close #14)
現在、BOT起動前にアーカイブされたThreadChannelを取得出来ない問題があり、その挙動からCache周りが原因である可能性があると考えていますが、他に気になる点があれば指摘していただきたく思い、DraftとしてPRを開きます。

2022-08-19 23:29 UTC, anatawa12 requested changes

2022-08-19 23:29 UTC, anatawa12 commented on src/main/kotlin/io/github/kobi32768/quotebot/DiscordChannel.kt
> +        is TextChannel, is VoiceChannel, is NewsChannel -> {
is IAgeRestrictedChannel でいいのでは

2022-08-19 23:29 UTC, anatawa12 commented on src/main/kotlin/io/github/kobi32768/quotebot/DiscordChannel.kt
> +            (this.parentChannel as StandardGuildMessageChannel).isNSFW
この関数をGuildChannel.isNSFW()にして、再帰的に呼び出しのほうがキャストがなくてきれいだと思います。StackOverflowを気にするのであればtailrecをfunの前につければいいと思います。

2022-08-19 23:35 UTC, anatawa12 requested changes

2022-08-19 23:35 UTC, anatawa12 commented on src/main/kotlin/io/github/kobi32768/quotebot/DiscordMessage.kt
> +    return if (category != null) {
```
var title = "from: "
if (category != null) title += "${category.name} / "
title += channel.name
if (thread != null) title += " / ${thread.name}"
title += " (${guild.name})"
```

2022-08-20 03:13 UTC, Sayamame-beans commented on src/main/kotlin/io/github/kobi32768/quotebot/DiscordChannel.kt
> +        is TextChannel, is VoiceChannel, is NewsChannel -> {
確かに。

2022-08-20 03:22 UTC, Sayamame-beans commented on src/main/kotlin/io/github/kobi32768/quotebot/DiscordChannel.kt
> +            (this.parentChannel as StandardGuildMessageChannel).isNSFW
確かに、再帰にすればSmart castだけで通せそうですね。
GuildChannelの方が良いというのは…なるほど、`this.parentChannel`が`IThreadContainerUnion`であるためですかね?

StackOverflowのことは考えていませんでした…

2022-08-20 03:24 UTC, Sayamame-beans commented on src/main/kotlin/io/github/kobi32768/quotebot/DiscordMessage.kt
> +    return if (category != null) {
今の形にするか、Stringの連結で書くか迷ったんですが、やはりそちらの方が簡潔ですか…

2022-08-20 06:45 UTC, anatawa12 commented on src/main/kotlin/io/github/kobi32768/quotebot/DiscordChannel.kt
> +            (this.parentChannel as StandardGuildMessageChannel).isNSFW
> GuildChannelの方が良いというのは…なるほど、this.parentChannelがIThreadContainerUnionであるためですかね??

そうです

2022-08-20 07:24 UTC, Sayamame-beans commented on src/main/kotlin/io/github/kobi32768/quotebot/DiscordChannel.kt
> +        is TextChannel, is VoiceChannel, is NewsChannel -> {
対応を行いました。

2022-08-20 07:24 UTC, Sayamame-beans commented on src/main/kotlin/io/github/kobi32768/quotebot/DiscordChannel.kt
> +            (this.parentChannel as StandardGuildMessageChannel).isNSFW
対応を行いました。

2022-08-20 07:24 UTC, Sayamame-beans commented on src/main/kotlin/io/github/kobi32768/quotebot/DiscordMessage.kt
> +    return if (category != null) {
対応を行いました。

2022-08-20 08:40 UTC, anatawa12 requested changes

2022-08-20 08:40 UTC, anatawa12 commented on src/main/kotlin/io/github/kobi32768/quotebot/DiscordChannel.kt
> +    }
こんだけ各ブランチが短ければ、
```
tailrec fun GuildChannel.isNSFW(): Boolean = when (this) {
    is IAgeRestrictedChannel -> this.isNSFW
    is ThreadChannel -> this.parentChannel.isNSFW()
    else -> false
}
```
みたいに短くしたほうが見やすいと思ってます

2022-08-20 08:55 UTC, Sayamame-beans commented on src/main/kotlin/io/github/kobi32768/quotebot/DiscordChannel.kt
> +    }
ふむ…一理あります。
`->`後の`{}`除去についてはすぐに行います。
しかしながら、`Utility.kt`など、`fun name: type = value`の形になっていないものが既に存在するため、`return`は残したままにした方が一貫性があると思いますがいかがでしょうか?

2022-08-20 09:14 UTC, anatawa12 commented on src/main/kotlin/io/github/kobi32768/quotebot/DiscordChannel.kt
> +    }
`=`の後が`when (this) {` のみと短いので、これはやったほうがいいと思います。
`Utility.kt`内のはおおくは`=`にするとまぁ長いので、私もやらない判断する程度です。

2022-08-20 09:20 UTC, Sayamame-beans commented on src/main/kotlin/io/github/kobi32768/quotebot/DiscordChannel.kt
> +    }
なるほど、理解しました。

2022-08-21 06:09 UTC, anatawa12 approved these changes

2022-08-22 07:26 UTC, merged